#baikal_dav_services_caldav_problem:
#    pattern: /cal/calendars/admin/
#    defaults: { _controller: BaikalDavServicesBundle:Caldav:problem, slug: null }
#    methods: ['PROPPATCH']

baikal_dav_services_caldav:
    pattern:  /cal/{slug}
    defaults: { _controller: BaikalDavServicesBundle:Caldav:index, slug: null }
    requirements:
        slug: ".*"

baikal_dav_services_carddav:
    pattern:  /card/{slug}
    defaults: { _controller: BaikalDavServicesBundle:Carddav:index, slug: null }
    requirements:
        slug: ".*"