services:

    baikal.davservice.pdoconnection.factory:
        class: Baikal\DavServicesBundle\Service\PDOConnectionServiceFactory
        arguments:
            - @doctrine.dbal.default_connection

    baikal.davservice.pdoconnection:
        class: PDO
        factory_service: baikal.davservice.pdoconnection.factory
        factory_method: get

    baikal.davservice.backend.authentication:
        class: Sabre\DAV\Auth\Backend\PDO
        arguments:
            - @baikal.davservice.pdoconnection

    baikal.davservice.backend.caldav:
        class: Baikal\DavServicesBundle\Service\DAV\BaikalCaldavPDOBackend
        arguments:
            - @baikal.davservice.pdoconnection

    baikal.davservice.backend.principal:
        class: Sabre\DAVACL\PrincipalBackend\PDO
        arguments:
            - @baikal.davservice.pdoconnection

    baikal.davservice.plugin.authentication:
        class: Sabre\DAV\Auth\Plugin
        arguments:
            - @baikal.davservice.backend.authentication
            - %baikal.dav_realm%

    baikal.davservice.plugin.caldav:
        class: Sabre\CalDAV\Plugin

    baikal.davservice.plugin.acl:
        class: Sabre\DAVACL\Plugin

    baikal.davservice.plugin.htmlbrowser:
        class: Sabre\DAV\Browser\Plugin

    baikal.davservice.plugin.sync:
        class: Sabre\DAV\Sync\Plugin

    baikal.davservice.calendar.factory:
        class: Baikal\DavServicesBundle\Service\DAV\CalendarServiceFactory
        arguments:
            - @baikal.davservice.backend.principal
            - @baikal.davservice.backend.caldav
            - @router
            - "baikal_dav_services_caldav"
            - 
                - @baikal.davservice.plugin.authentication
                - @baikal.davservice.plugin.caldav
                - @baikal.davservice.plugin.acl
                - @baikal.davservice.plugin.htmlbrowser
                - @baikal.davservice.plugin.sync

    baikal.davservice.calendar:
        class: Sabre\DAV\Server
        factory_service: baikal.davservice.calendar.factory
        factory_method: get

    # Security

    baikal.davservices.authorization_voter:
        class: Baikal\DavServicesBundle\Security\Authorization\Voter\DavServicesAuthorizationVoter
        public: true
        arguments:
            #- @security.context # LAZY LOADED to avoid circular dependency
            - @service_container
            - @config.main
        tags:
            - { name: security.voter }

    # Helpers

    baikal.helper.davtimezonehelper:
        class: Baikal\DavServicesBundle\Service\Helper\DavTimeZoneHelper
        arguments:
            - @config.main